package conexiondb.pojos;
// Generated Jun 10, 2022 7:35:30 AM by Hibernate Tools 4.3.1



/**
 * Regla generated by hbm2java
 */
public class Regla  implements java.io.Serializable {


     private Integer id;
     private int rangoinicial;
     private int rangofinal;
     private String mensaje;
     private String destinatario;

    public Regla() {
    }

    public Regla(int rangoinicial, int rangofinal, String mensaje, String destinatario) {
       this.rangoinicial = rangoinicial;
       this.rangofinal = rangofinal;
       this.mensaje = mensaje;
       this.destinatario = destinatario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getRangoinicial() {
        return this.rangoinicial;
    }
    
    public void setRangoinicial(int rangoinicial) {
        this.rangoinicial = rangoinicial;
    }
    public int getRangofinal() {
        return this.rangofinal;
    }
    
    public void setRangofinal(int rangofinal) {
        this.rangofinal = rangofinal;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }




}


